### PR TITLE
Make e2e test suite work with ap test file (coverage=41%)

### PR DESCRIPTION
**Pull request by joanise**
Use Aidan's own voice recoding in Gitxsan to rehabilitate the force align test suite and include it in dev.

### CODE REVIEW

**Comment by joanise** [comment]
Hum, I'm obviously not calculating coverage the same way. On my machine, I get 41%, here coveralls reports only 21%. I'll have to investigate the difference.

**Comment by roedoejet** [comment]
Looks like there are a few files that it's not finding for your alignment tests:

`FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/build/dhdaines/ReadAlong-Studio/test/data/ap.txt'`

The path should be `'/home/travis/build/dhdaines/ReadAlong-Studio/test/data/ap-git.txt'` no? In test_force_align you're pointing to ap.txt and ap.xml etc, but they're named differently in the commit. That probably accounts for (at least part of) the missing coverage.

**Comment by roedoejet** [comment]
Can you fix that, commit and push again? I'll happily merge it after.

**Comment by roedoejet** [comment]
> Can you fix that, commit and push again? I'll happily merge it after.

Nevermind! I forgot it was late out east. I just made the changes and I'll accept this now.

**Comment by joanise** [comment]
Sorry Aidan, I made the changes in my sandbox, exactly what you did, but forgot to commit that file, and, as you guessed, I left work just then. Thanks for fixing it.

**Comment by roedoejet** [comment]
No worries, easy fix and it’s all checkmarks and green lights now. Thanks again, talk soon!

**Comment by joanise** [comment]
Glad to see coverage back at 41% with the patch on the file names. This reassures me that I'm doing the right thing on my own computer!

**Pull request merged**
