### PR TITLE
Updated g2p and refactoring

### PR DESCRIPTION
**Pull request by roedoejet**
Hey @dhdaines,

I've made a union of the functionality of @littell's index-preserving g2p library and the context-sensitive g2p library I've been developing and added it here. I've also done some other things like moved the command line code to its own file and refactored using the command line library bundled with Flask called Click. This allows us to leverage some of the parameter helpers and also run the studio with a simple command `readalongs run`.

I've also added a travis file that would set us up for automating our testing. Do you have a travis account? Would you be able to set that up? It doesn't seem like it's possible for me to add this repo to my travis account because I'm not the owner. I was also hoping to link it up with coveralls.io to get automatic coverage reports. 

Lastly, how do you feel about publishing to pypi under the namespace 'readalongs' - it's open and I can go ahead and do that if you and @littell think it's alright. I also updated our versioning system in anticipation of doing this.

Sorry for the big PR, let me know if you have any questions!

A

### CODE REVIEW

**Comment by roedoejet** [comment]
Oh, and I updated the README as well :)

**Comment by dhdaines** [comment]
Hi!  Sorry, I meant to reply to this earlier.  I keep saying I'll have time
to work on readalongs and not finding it but maybe, probably, this week!

In fact, maybe this evening.  I should be able to merge this then.  I will
have to read up on Travis, I don't actually know how it works!

**Comment by roedoejet** [comment]
No worries! Travis (kinda like Jenkins) is meant for automated testing and continuous integration. It works similarly to Docker in that you have a configuration file (.travis.yml) which specifies various dependencies to install and scripts to run. I put all our unit tests that don’t require private data into a TestSuite and the travis file first installs Python and all dependencies needed, clones the ReadAlong-Studio repo, spins up the web app, runs the test suite, and then sends a coverage report to coveralls.io <http://coveralls.io/> which visualizes the coverage report. Both Travis and Coveralls are free for open source projects which is why I like to use them.

Once you get a Travis account, you can link it with your GitHub, and then just flip a switch to turn on automatic builds. You can also set up things like emails or slack notifications when builds fail. I haven’t tested the travis file, so the build might fail, but let me know once you sign up (or I can look to see if there’s another way) and I can debug it if needed.

Thanks!

A

**Comment by roedoejet** [comment]
Hey @dhdaines I found a bug with mixing and matching some of the g2p types. Feel free to have a look at the rest of the code, but let's hold off on merging until I've fixed that, I'll have some time this afternoon!

**Comment by roedoejet** [comment]
> Hey @dhdaines I found a bug with mixing and matching some of the g2p types. Feel free to have a look at the rest of the code, but let's hold off on merging until I've fixed that, I'll have some time this afternoon!

Seems fixed as of 497b4d7

**Comment by roedoejet** [comment]
Also, I looked into it, and indeed there is no way for me to add your repo to my travis account. However, if you don't want to manage your own travis account, we could start a GitHub 'organization' account (https://help.github.com/en/articles/types-of-github-accounts#organization-accounts) for the readalongs in which case I would be able to use my travis account. I'm happy either way.

**Comment by dhdaines** [comment]
Great!  I am looking at this now but it seems okay to merge.  I set up Travis and Coveralls as well...

I think maybe we should have a bit better documentation before publishing to PyPI.  I hope to find some time to actually work on this project really soon (even though I've been saying that for a while, I know)

**Comment by roedoejet** [comment]
Ok, that makes sense. I was mostly just thinking about publishing to secure the namespace but I don't think we're really in danger of getting it swiped. Do you have a readthedocs account? I can get us set up with some Sphinx boilerplate tomorrow. Maybe we should Skype sometime to discuss how to tackle the documentation? I'm free this weekend or we can try next week?

**Comment by dhdaines** [comment]
I will get set up with readthedocs now!  Unfortunately this weekend I'm away from the Internet but next week would be good, let me know when you're available!

**Comment by dhdaines** [comment]
I looked over this and it looks good in general - no need for a full code review I think :) I'll merge it now!

**Comment by roedoejet** [comment]
Hi Roland,

I took care of Pine & Turin 2017, Whalen et al 2016, Reyhner 2010, Oster et al 2014, Marmion et al 2014, Chandler 1998, Maracle 2017 and Hallett et al 2007

Fastapi and CouchDB is not a reference, and Rebecca fixed my WordWeaver figure references.

Thanks!

A

P.S David’s email is dhdaines@gmail.com <mailto:dhdaines@gmail.com>

**Pull request merged**
